name: Check Commit Messages

on:
  pull_request:
    branches: [main]

jobs:
  check-commits:
    uses: http://gitea.int.superwerewolves.ninja:3000/super-werewolves/gitea-deploy-actions/.gitea/workflows/check-commits-reusable.yml@main
